name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia 00:00 UTC
  workflow_dispatch:      # permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    # PERMISSÕES PARA O GITHUB_TOKEN
    permissions:
      contents: write

    steps:
      - name: Gerar snake (contribuições)
        uses: Platane/snk@v3
        with:
          github_user_name: calielfelipo
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
